realcar_path: /nas/users/hyzhou/PAMI2024/release/3DRealCar
model_base: /nas/users/hyzhou/PAMI2024/release/outputs/nusc
uniad_path:  /nas/users/hyzhou/PAMI2024/release/UniAD_Sim/tools/e2e.sh
vad_path:  /nas/users/hyzhou/PAMI2024/release/VAD_Sim/tools/e2e.sh
ltf_path: /nas/users/hyzhou/PAMI2024/release/navsim/ltf_e2e.sh
output_dir: /nas/users/hyzhou/PAMI2024/release/outputs/benchmark/out/nusc_
HD_map:
  path: /nas/datasets/nuScenes/raw/Trainval
  version: nusc_trainval