realcar_path: /nas/users/hyzhou/PAMI2024/release/3DRealCar
model_base: /nas/users/hyzhou/PAMI2024/release/outputs/waymo
uniad_path: /nas/users/hyzhou/code/UniAD_Sim/tools/e2e.sh
vad_path: /nas/users/hyzhou/code/VAD_Sim/tools/e2e.sh
ltf_path: /nas/users/hyzhou/code/navsim/ltf_e2e.sh
output_dir: /nas/users/hyzhou/PAMI2024/release/outputs/benchmark/out/waymo_